hl.env("XDG_CURRENT_DESKTOP","Hyprland")
hl.env("XDG_SESSION_TYPE","wayland")
hl.env("XDG_SESSION_DESKTOP","Hyprland")
hl.env("XCURSOR_SIZE","24")
hl.env("QT_QPA_PLATFORMTHEME","qt6ct") -- change to qt6ct if you have that
hl.env("WLR_NO_HARDWARE_CURSORS","1")
hl.env("MANGOHUD","1")
hl.env("LIBVA_DRIVER_NAME","nvidia")
hl.env("__GLX_VENDOR_LIBRARY_NAME","nvidia")
hl.env("ELECTRON_OZONE_PLATFORM_HINT","auto")
hl.env("NVD_BACKEND","direct")
