-- Generated by nwg-displays on 2026-07-04 at 16:17:10. Do not edit manually.

hl.monitor({
    output = "desc:BOE NE135A1M-NY1",
    mode = "2880x1920@60.0",
    position = "0x0",
    scale = 2.0
})
