# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# windowrulev2 = nomaximizerequest, class:.* # You'll probably like this.

# For Steam's Pop-up windows
windowrule {
    name = steam
    match:title = ^(steam)$
    match:class = ^(steam)$

    stay_focused = on
}

# For the GNOME Calculator
windowrule {
    name = calculator
    match:title = ^(Calculator)$
    match:class = ^(org.gnome.Calculator)$

    float = on
}
